### PR TITLE
LL devnet express cloud collab code examples

### PR DESCRIPTION
**Pull request by ReneeBornstein**
Updated contributing and added Makefile to Repo

### CODE REVIEW

**Review by annegentle — APPROVED** [review]

**Review by annegentle — APPROVED** [review]

**Comment by annegentle** [comment]
Oh, this repo does not need a `Makefile`.

**Comment by ReneeBornstein** [comment]
Can we leave it in the Repo, or do we need to remove it? I’m not sure how to remove a file from the Repo. I can do that in my desktop, of course, but I’m not sure how to make a branch that removes a file. I could make the file have no text, but there’s probably a better way to do it.

**Comment by annegentle** [comment]
I already reverted the branch that added the `Makefile`, so you don't need to do anything additional.

**Comment by ReneeBornstein** [comment]
Okay. Thanks!

**Pull request merged**
